### PR TITLE
Review Dispute

### PR DESCRIPTION
**Pull request by mason-bially**
This book is not cyberpunk, except perhaps in that it is a *realistic* depiction of cyberpunk (and without the punk nor the cyber). Augmented reality in this case being holo lens like technologies, and importantly, relying on physical reality for things beyond sight and sound. This is a near future prediction book by a computer science professor, all commonplace technologies in the book are well researched and founded on technology trends (of 2006). There are sci-fi gimmies relevant to the plot, but they are all quite constrained and even within the realm of possibility (though not probability) within the next 30 years.

Without issues there really isn't a dispute or discussion system.

There is a with-the-permission-of-the-author free copy [on the web here](https://www.talisman.org/~erlkonig/misc/vernor-vinge%5Erainbows-end.html) (except that it's not really meant for general distribution (though it's the second search result) so I will not propose linking it on the page, but I will link it here to you) if you wish to read it yourself, I would recommend reading through to the end of chapter 1 (as it displays the tone and common technology of the book) and see if it seems like it commits the sins of cyberpunk and judge it's score with that.

@fiftysevendegreesofrad

### CODE REVIEW

**Comment by fiftysevendegreesofrad** [comment]
Thanks for the heads up. I will have a look at your link when I've a moment :)

**Comment by fiftysevendegreesofrad** [comment]
I read the first chapter last night - agree it's good, I certainly want to continue. Let's have it on the list for sure. 

That said, you leave me wondering whether I've properly communicated what I mean by comp-fi (thank you for making me think harder about this): VR/AR alone does not qualify so I wonder if Rainbows End merits 5 for compsci proportion or centrality. What I meant by saying your review makes it sound like cyberpunk is certainly not a slur - what I mean is it appears to focus on societal implications of computing rather than the underlying concepts. Like you say, cyberpunk without the cyber or the punk. If you compare the works on the list with high comp-fi proportion scores there is a lot more focus on underlying concept than social implication (at least there was when I first wrote the list - admittedly it has changed since). I haven't yet seen anything in the book or your review to suggest otherwise (can you point me at another chapter?). 

I don't want to be a gatekeeper for the list so I'll accept your edit, anyway, up to you if you want to change those scores, and put my own placeholder review in based on chapter 1.

**Comment by mason-bially** [comment]
I guess rereading the blurb on the site I'm not sure I understand the difference very well. What is excellent about Vernor Vinge's works in general is that he weaves a believable world and story that focuses on many aspects of a technology (and Rainbows End has dozens of them, unlike his normal sci-fi books which have just a few very specific ones). Not just societal aspects, but how things work at progressively deeper levels. If you are willing to let me ruin a lot of that experience I could barrel ahead and link some chapters that describe that (at one point Vinge wrote a detailed explanation behind one of the technologies that was supplemental, but I can't see to find it).

I'm also not sure what you mean by underlying concepts compared to social consequences. Social consequences follow from the underlying concepts. He doesn't always layout exactly how everything works because large parts of this are speculative. As people aware of how software works we can read a sentence of his, in the context of the world, and imagine exactly what an API for that might look like, but he never really goes as deep as being that specific. What makes it so central is the richness and interaction of these technologies; the central plot has barely anything to do with computation directly, but every decision the characters make as part of that plot is informed and shaped by technology, especially computational technology, and the point here is that in the future all of these wonderus computational devices will just be another part of our life. And importantly that he wrote this 15 years ago and many of the predictions are already true (influencers, hobbyist investigations, cryptocurrency smart contracts, pokemon go/harry potter AR, being the most striking to me), it may be different to me that his predictions were so on the nose because I read the book near when it came out.

Stop now if you just want to read it yourself.

So in an attempt of some short excerpts, of a piece of interlinked world building, all of these are central to the plot, but as actions people do, the core concepts are sort of just implied (but in many different chapters from different viewpoints; if you already know what it is it's interesting, and if you don't you get a decent idea of it):
* The last section of Chapter 21 describes changing out integrated wearable computing for illegal open source hardware.
* The first section of Chapter 22 describes how that illegal hardware works to provide normal features, touches on milnets.
* The first section of Chapter 28 describes a certificate revocation in a world where all legitimate devices have certificates.

But they only make sense because of the world building in the previous chapters. Computation made it easier to machine things (like 3d printing and automated biological manipulation) that could be massively dangerous (and were; 3d print a nuke, design a plague in your garage). In response governments made a secure hardware environment, that would only be snooped on for massively dangerous (and not like fraud, drugs, and murder) crimes. This made lots of open source hardware and software illegal. This made it necessary to have certificates on every piece of hardware, and every piece of content (this allows for micro licensing, rather than just ads; is a cool tangent, but there are dozens of tangents out from all the things I just described that are explored).

Chapter 31 is pretty short and is sort of the height of the climax (and lots of hints at spoilers), it builds on the world building above, and more besides, it's a cool chapter to read. But it includes a pretty great exchange important to a decision a character makes that is central to the plot, that I think is illustrative of this style (without giving away too much since the revocation attack is in the table of contents):

> \<point-of-order>I have a sanity check. We've lost communication with five percent of our original threat analysts since the revocation attack began. This should be impossible.\</point-of-order> All analysts were internal to the U.S. intelligence community. If Credit Suisse certificates were necessary for any of those participants to maintain connectivity, then there was at least a design failure ... and maybe the enemy had been part of Bob's own support staff.
>
> There was an immediate counter-argument:
>
> \<point-of-order>You're mistaking loss of connectivity for loss of trustability.\</point-of-order>
>
> Then parts of the analyst pool got jammed in the controversy. It was the kind of deadlock that only a miracle-worker could quickly untangle.

**Comment by fiftysevendegreesofrad** [comment]
Thanks for your reply. I'm staying spoiler averse - I'm a few chapters in now and will come back to it when I finish the book :)

**Pull request merged**
