### PR TITLE
Add Permutation City, change Cryptonomicon to long, fix small grammar issue.

### PR DESCRIPTION
**Pull request by dfockler**

### CODE REVIEW

**Comment by robwwilliams** [comment]
Absolutely agree. Permutation City and several other Egan works belong here such ad Shield’s Ladder which begins: “In the beginning was a graph, ....” Scoring 5+

**Comment by LaikaFusion** [comment]
Sorry about that copied the format on Cryptonomicon but forgot to change length. 

Please also remove Free to Download as it's not

**Comment by briangordon** [comment]
Permutation City +++++++++++++++++++++++++++++++

**Comment by fiftysevendegreesofrad** [comment]
Hi. I have incorporated your changes in the new version (instead of pulling). They include some guesses as I changed the score system - you may wish to check!

**Comment by dfockler** [comment]
Looks good 👍

**Pull request closed without merging**
